### ISSUE TITLE
Interactive plots for large sumstats

### ISSUE THREAD

**Issue by michaelofrancis** [anastasia-lucas/hudson#18]
Hi, I am trying to make an interactive plot for summary statistics that have ~8m variants.

I'm just trying to enable interactive for variants with P<5e-05 while keeping the rest of the variants as regular dots.

Here's what I have tried:

file$Link=""
file$Link[file$pvalue<5e-05] <- paste0("https://www.ncbi.nlm.nih.gov/snp/", file$SNP[file$pvalue<5e-05])

And similarly:
file$Link=NA
file$Link[file$pvalue<5e-05] <- paste0("https://www.ncbi.nlm.nih.gov/snp/", file$SNP[file$pvalue<5e-05])

In both cases I get this error:

Error in paste0(readLines(con = path, encoding = encoding, warn = warn,  : 
  result would exceed 2^31-1 bytes
Calls: igmirror -> <Anonymous> -> read_file -> paste0

Your demo files use all the lines and I'm not sure what to do. Any help would be appreciated! Thanks.

**Comment by anastasia-lucas** [comment]
Hi, thanks for using the package.

Around how many SNPs are you getting at <5e-05? The example data only has around ~5K SNPs per dataset. 

Unfortunately for the interactive plots, it's really difficult to plot more than ~50K variants or so. I'd recommend maybe doing some random filtering of the variants that you'd like to leave as dots or only plotting based on a significance threshold entirely.

Another option is to try adding a `geom_raster()` layer for the points that you don't want to link (also would not have hover available), but you would need to slightly modify the `igmirror()` function to do that.

**Comment by michaelofrancis** [comment]
Hi, thanks for the quick response! In the current sumstats I'm using, there are about 800 variants at P<5e-05 and about 8 million other variants at P>5e-05. 

I thought of plotting only the significant dots but that makes for an incomplete looking Manhattan plot. I think adding the geom_raster for these other points that don't need link/hover would be the right solution. I don't know if I will be able to do that myself, but I would really appreciate it if someone on your team can add that feature. I think this would be very helpful to most users of the software since having variants in the millions is probably the typical current situation, right? If this can get done relatively soon I'll definitely include Hudson in our upcoming manuscript.

Thanks!

**Comment by anastasia-lucas** [comment]
Yes, I agree it would be a great feature to have since most will want the traditional Manhattan plot "look." I can try to add this in the next few days. 

Unfortunately the team is just me and I'm not funded for this project anymore, so I cannot 100% guarantee. However I will provide an update sometime next week (and if I don't for some reason please feel free to ping me again :) )

**Comment by michaelofrancis** [comment]
Sounds great, thank you.

**Comment by anastasia-lucas** [comment]
Hi, I made a quick & dirty change to `igmirror()` on this branch https://github.com/anastasia-lucas/hudson/tree/dev-raster which is not a permanent change but I think should work for you for now. 

You can install the branch using the command `devtools::install_github("anastasia-lucas/hudson", ref = "dev-raster")`

Please note that this necessitated a new argument called `hover_threshold` which is defaulted to only apply tooltips to SNPs that have either the GWAS 5e-8 significance or have user-specified Links.  This will only be used if you do not specify a `Hover` column in your data. Based on your example, I think as long as you selectively set Links for p<5e-05 (and NA otherwise), it should work as expected without modifying any of your original code. See e.g. below

```
data(gwas.t)
data(gwas.b)
gwas.t$Link <- ifelse(gwas.t$pvalue < 0.05/nrow(gwas.t), paste0("https://www.ncbi.nlm.nih.gov/snp/", gwas.t$SNP), NA)
gwas.b$Link <- ifelse(gwas.b$pvalue < 0.05/nrow(gwas.b), paste0("https://www.ncbi.nlm.nih.gov/snp/", gwas.b$SNP), NA)
igmirror(top=gwas.t, bottom=gwas.b, tline=0.05/nrow(gwas.t), bline=0.05/nrow(gwas.b),
              toptitle="GWAS Comparison Example: Data 1", bottomtitle = "GWAS Comparison Example: Data 2",
              highlight_p = c(0.05/nrow(gwas.t), 0.05/nrow(gwas.b)), highlighter="green")

```

I did need to install XQuartz in order for the raster part to work correctly (MacOS, untested on other). Otherwise you will probably get an error complaining about Cairo when you save the html.

**Comment by michaelofrancis** [comment]
It works! Thank you so much for how fast you took care of this. 
Cheers!
