### ISSUE TITLE
phemirror Plotting Issue

### ISSUE THREAD

**Issue by katya-dun** [anastasia-lucas/hudson#2]
Hi, 

I am hoping I can get some help with an issue I'm finding with the phemirror function. When running with limited phenotypes (max 11), the function works fine and I get the expected plot. However, when running with many phenotypes (over 60), the top legend seems to cover the top plot. I have attached an image. Any reason this may be happening? The file is in the same format as the others I've tried with, just with more traits. 
<img width="1196" alt="Screen Shot 2019-03-26 at 10 54 23 PM" src="https://user-images.githubusercontent.com/39524530/55047313-ae96c900-501a-11e9-8df3-71d8a8de78e5.png">

Thanks

**Comment by anastasia-lucas** [comment]
I am incredibly sorry I never saw a notification for this issue as I haven't been updating this package much. Please in the future feel free to e-mail me as well at anastasia.lucas.bioinfo@gmail.com (also listed in the package description file). I think unfortunately this was an artifact of of the legend having so many categories. Have you tried changing the `hgtratio` parameter? If this doesn't work I am happy to help further, assuming you haven't already found a solution since the issue was posted
